# Generated by Django 6.0.6 on 2026-07-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_alter_contactmessage_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
